### ISSUE TITLE
Pass $ST2_RELEASE to docker-compose from CI

### ISSUE THREAD

**Issue by armab** [dennybaa/st2-packages#12]
Add ability to pass revision number aka release number from CI, to control package versioning.
> st2api_0.14dev-**20**_amd64.deb

So the version number `0.14dev` is parsed from [`st2common`](https://github.com/StackStorm/st2/blob/master/st2common/st2common/__init__.py#L16) automatically and revision number `20` is injected from outside via ENV.

Same as we have for mistral [in docker-compose](https://github.com/dennybaa/st2-packages/blob/4c356bf7b908fd27bdfdfa865cb93b326985f94a/compose-suite.yml#L19).

`docker-compose` should pick up env via https://github.com/docker/compose/pull/1765 when using:
```sh
export ST2_RELEASE=20
docker-compose up debian
```
--- 

^^ I'm happy that feature with ENV variables was introduced in docker-compose and released in [1.5 version just *hours ago*](https://github.com/docker/compose/releases/tag/1.5.0). We're lucky here :four_leaf_clover: 

Docs: https://github.com/docker/compose/blob/8cc8e61/docs/compose-file.md#variable-substitution

**Comment by dennybaa** [comment]
:+1:

**Comment by armab** [comment]
Worked flawlessly in https://github.com/armab/st2/blob/5736f16a58dbfdc9b30eafb5dc0b959c98f096a9/circle.yml#L51

Thanks to Docker :+1:
