### ISSUE TITLE
docker-compose doesn't redirect subprocess exit code

### ISSUE THREAD

**Issue by armab** [dennybaa/st2-packages#15]
Meaning if `docker-compose up ubuntu` command errored with all st2 package tests, - we won't know.

* Workaround 1: `docker-compose run` instead of `up`, but it doesn't works in AWS #2, Vagrant #4
* Workaround 2: Check if any of containers exited with non-zero code via: `docker-compose ps` http://stackoverflow.com/a/33291554/4533625

**Comment by dennybaa** [comment]
@armab could you please make a PR for this

**Comment by armab** [comment]
Sure, I'm creating these issues as a reminders/TODO.

Will try to go with `docker-compose run` with renewed build process, since it's preferred way.
If no, Workaround 2 should work in `circle.yml`.

**Comment by armab** [comment]
Confirming that `docker-compose run` works now in both `Vagrant` #4 and in CircleCI with new ruby way.

Even the output is colored :laughing: 
![docker-compose-run](https://cloud.githubusercontent.com/assets/1533818/11036964/96a0e006-86fb-11e5-8d5c-6108b876563d.gif)




So switching from `docker-compose up` to `docker-compose run` fixes this issue, since `run` exits with suprocess exit code.

**Comment by dennybaa** [comment]
I know man :100:  Should be)
