### ISSUE TITLE
Artifacts Build Time/Speed

### ISSUE THREAD

**Issue by armab** [dennybaa/st2-packages#7]
#### The Problem

Let's talk about build time/build speed. The problem is that the time of build is big (no surprises here).
   * `~15min` - for `debian`
   * `~18min` - for `ubuntu`
   * `~27min` -  for `centos7`

Considering that for now everything is minimal and *real* build time is time of the slowest build - we have minimum half of hour to wait before getting any results and we should tie that with GitHub Pull Request status, so the developer can see status ASAP.

This timing is not reliable enough.

#### The Reason

I thought it's slow because of 3rd party CI, but here are my stats for `docker-compose up debian` running on AWS `c4.large` (2 vCPUs, 8 ECUs, 3.5 GiB RAM) which is good CPU-optimized machine: 
> 16 minutes total (4-5 minutes from that took pulling Docker images)
Same timing as we have on CI systems.

Noticed that CPUs were not used very heavily during the build. Saw the same when SSH debugged CircleCI (which has 32 CPUs for one VM) and as you see, almost the same results running in good AWS instance. 

So it looks like we need some solution to better use these horse powers and speed up the builds.
For example further parallelize stage when `st2-*` packages are built (it's biggest and slowest part of entire process). 

As I understand, for the moment all packages `ST2_PACKAGES="st2common st2actions st2api st2auth st2client st2reactor st2exporter st2debug"` are building one-by-one.

#### Ideas (without research and possible solutions): 
* Caching
  * for docker pull when Docker images are downloaded (it takes from 2 to 5 minutes) (?)
  * for downloading pip packages (?)
  * using built-in CI for Mongo/PostgreSQL/RabbitMQ instead of Docker container (CircleCI and TravisCI have these services preinstalled) (?)
* Decrease build time for `st2-*` packages in one distro (linear build -> parallel build):
  * fork async build processess in one Docker container and wait for longest to finish (?)
  * `BUILDHOSTS` instead of `BUILDHOST` - to build the `st2` packages inside several Docker containers in parallel (?)

----

What can we think about/do else? Or don't worry for now, improve it later?

**Comment by dennybaa** [comment]
resolved look at #11

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1454358262003967

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1455090248006316
